### ISSUE TITLE
Cannot build (Go 1.8, Win7_64)

### ISSUE THREAD

**Issue by VinWz** [KingCrunch/mocksmtp#1]
Hi KingCrunch,

I am interested by your code ; however, I can't build it.
After git-getting it, I am getting the following errors when trying to build or install:

```
$ go build github.com/kingcrunch/mocksmtp
# github.com/kingcrunch/mocksmtp
src\github.com\kingcrunch\mocksmtp\functions.go:29: undefined: AssetNames
src\github.com\kingcrunch\mocksmtp\functions.go:30: undefined: Asset
src\github.com\kingcrunch\mocksmtp\http.go:18: undefined: assetFS

$ echo $?
2
```
Sorry if I am missing something huge, as I am fairly new to GoLang.
Are you using any AssetFS package or such (tried importing github.com/elazarl/go-bindata-assetfs/blob/master/assetfs.go but it does not appear to be this one)?

I am using git bash on Windows with the latest Git 1.8.

Your help will be much appreciated.
Thanks!

**Comment by KingCrunch** [comment]
Hi,

I use [go-bindata-assetfs](https://github.com/elazarl/go-bindata-assetfs) to include some assets into the binary. This means, there are some additional steps required.

```
go get github.com/elazarl/go-bindata-assetfs/...
go get github.com/jteeuwen/go-bindata/...
go generate
govendor sync
```

After that `go build` should work as expected. I don't develop, or even use windows, but for Linux I've created a (slightly incomplete) `Makefile`, which also shows the required steps.
